del "%~dp0*.cs"
del "%~dp0Kernels\*.cs"
del "%~dp0App\*.cs"
del "%~dp0Domain\*.cs"
del "%~dp0Infra\*.cs"
copy "%~dp0..\DomainShell\*.cs" "%~dp0"
copy "%~dp0..\DomainShell\Kernels\*.cs" "%~dp0Kernels"
copy "%~dp0..\DomainShell\App\*.cs" "%~dp0App"
copy "%~dp0..\DomainShell\Domain\*.cs" "%~dp0Domain"
copy "%~dp0..\DomainShell\Infra\*.cs" "%~dp0Infra"